on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Run tests
      run: make test
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)